# Generated by Django 4.2.6 on 2023-10-19 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yonalish',
            options={'verbose_name': 'Fan', 'verbose_name_plural': 'Fanlar'},
        ),
    ]
